# Generated by Django 3.2.5 on 2021-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210829_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Артикль'),
        ),
    ]
