# Generated by Django 3.2.5 on 2021-08-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'ПРОДУКТ Артикул', 'verbose_name_plural': 'ПРОДУКТЫ Артикулы'},
        ),
    ]
