# Generated by Django 3.2.5 on 2021-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210829_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
