# Generated by Django 3.2.5 on 2021-08-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderentity',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ Юридическое лицо', 'verbose_name_plural': 'Заказ Юридические лица'},
        ),
        migrations.AlterModelOptions(
            name='orderphysical',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ Физический', 'verbose_name_plural': 'Заказы Физические'},
        ),
    ]
