# Generated by Django 3.2.5 on 2021-09-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210829_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentity',
            name='payment_type',
            field=models.CharField(choices=[('Банковские переводы на расчетный счёт', 'Банковские переводы на расчетный счёт'), ('Перевод на карту', 'Перевод на карту')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderphysical',
            name='payment_type',
            field=models.CharField(choices=[('Банковские переводы на расчетный счёт', 'Банковские переводы на расчетный счёт'), ('Перевод на карту', 'Перевод на карту')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Стоимость')),
                ('size_chart', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размерная сетка')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Цвет')),
                ('order_phys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='orders.orderphysical')),
            ],
        ),
    ]
