# Generated by Django 3.2.5 on 2021-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productentity_productentityimage_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products_order', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productentity',
            name='image',
            field=models.ImageField(default=1, upload_to='products_order', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductEntityImage',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
