# Generated by Django 3.2.5 on 2021-09-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210921_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_phys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_phys', to='orders.orderphysical'),
        ),
        migrations.AlterField(
            model_name='productentity',
            name='order_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_entity', to='orders.orderentity'),
        ),
    ]
