# Generated by Django 3.2.5 on 2021-07-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name': 'КАТЕГОРИЯ', 'verbose_name_plural': 'КАТЕГОРИИ'},
        ),
    ]
