# Generated by Django 3.2.5 on 2021-07-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Наименование name'),
        ),
    ]
