# Generated by Django 3.2.5 on 2021-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Наименование Category'),
        ),
    ]
