# Generated by Django 3.2.5 on 2021-08-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование категории'),
        ),
    ]
