# Generated by Django 3.2.5 on 2021-08-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
