# Generated by Django 3.2.5 on 2021-08-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-id',), 'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
