# Generated by Django 3.2.5 on 2021-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210811_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_repeat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
