# Generated by Django 3.2.5 on 2021-08-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Email',
                'verbose_name_plural': 'Newsletters Email',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MessageNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Newsletter Message',
                'verbose_name_plural': 'Newsletters Message',
                'ordering': ('-id',),
            },
        ),
    ]
