# Generated by Django 3.2.5 on 2021-08-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getemail',
            options={'ordering': ('-id',), 'verbose_name': 'Новостная рассылка Email', 'verbose_name_plural': 'Новостные рассылки Email'},
        ),
        migrations.AlterModelOptions(
            name='messagenewsletter',
            options={'ordering': ('-id',), 'verbose_name': 'Информационный бюллетень', 'verbose_name_plural': 'Информационные бюллетени'},
        ),
    ]
